name: "airmen_fitness_scorecard_submitted"
pack: "cws_inform_mdang"
description: "Receive incoming webhook when scorecard is submitted"
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "mdang/scorecard_submitted"

action:
  ref: "cws_inform_mdang.notify_fitness_team"
  parameters:
    name: "{{trigger.body.ticket.airman_name}}"
    category: "{{trigger.body.ticket.category}}"
    abs_score: "{{trigger.body.ticket.abdominal_circumference_score}}"
    push_score: "{{trigger.body.ticket.push_up_score}}"
    sit_score: "{{trigger.body.ticket.sit_up_score}}"
    run_score: "{{trigger.body.ticket.run_walk_score}}"
    overall_score: "{{trigger.body.ticket.points_earned}}"